### ISSUE TITLE
Everytime I login it says system error please try again later

### ISSUE THREAD

**Issue by pinkisdead** [Grasscutters/Cultivation#132] opened 2023-02-13 09:58 UTC
bro how tf do i fix i already followed all instructions and connected to the proxy i have followed everything correctly and it still doesnt work

**Comment by pinkisdead** [comment] 2023-02-13 10:00
I also turned of encryption and didnt tick the https on my local server

**Comment by NotThorny** [comment] 2023-02-13 10:05
This is really just a duplicate of #127 and I'd suggest the same to you, to go to the [Grasscutter discord](https://discord.com/invite/grasscutters) for specific help, since this really is most likely an issue with your Grasscutter configuration. 
You probably haven't restarted the server yet if you disabled useEncryption and useInRouting (or used the button in settings). 
Though it may also be a problem with your address/port/https in Cultivation. For localhost on Cultivation, you need to use port 443 and no https

**Comment by pinkisdead** [comment] 2023-02-15 11:17
ok i found out i havent patched ua but how do i patch it

**Closed** 2023-03-23 15:36 UTC
